### PR TITLE
Allow opting out of changing shell to zsh

### PR DESCRIPTION
**Pull request by monfresh**
**Why**: For a better user experience

### CODE REVIEW

**Comment by monfresh** [comment]
Here's a screenshot of the text when the script first detects that you have bash installed, as well as the text that appears after you agree to switch to zsh, which explains how to switch back to bash.

screen shot 2017-01-05 at 4 14 51 pm

cc @brittag

**Comment by pkarman** [comment]
I have not tested, but +1 to the feature idea. I always have to switch my shell back manually as it is.

Code looks sane.

**Comment by stvnrlly** [comment]
If possible, it might help to run that prompt by a non-technical user. While I'd be comfortable with it, I have a feeling that it's easy for a new Terminal user to get lost for a few reasons:

- What's a "shell"? Is that different than "Terminal"? Why would the type of shell matter to me?
- The prompt says to `Press y`, but the user'd also have to hit return. I've seen this trip people up as they expect something to happen immediately after pressing the button.
- The password field won't give input feedback. This often leads new users to think that they're not actually entering anything.
- The prompt gives instructions for changing the shell later, but those instructions will be more useful then than now.

It seems to me that the type of shell will primarily matter to users who have already used shells a bit. As a result, it may be simpler to allow that choice to be set in a config file, which could either be distributed with the script, written beforehand, or interactively created via `bash mac --configure`. It may also help to include a `bash mac --change-shell` that also provides the instructions included in the screenshot above.

**Comment by brittag** [comment]
As one of the people who asked for a warning on this, I'm already familiar with shells and was surprised when the laptop script changed mine without asking; I'd also be surprised if I ran it and later learned I was supposed to configure this option in a file before running the script. :)

This could be simplified to:

> Want to switch your shell from the default `bash` to `zsh`? Both work fine for development, and `zsh` has some extra features for customization and tab completion. If you aren't sure or don't care, we recommend `zsh`.
> Press `y` (and enter) to switch to zsh, `n` (and enter) to keep bash.

I wouldn't try explaining the concept of shells here, since it's not something a person needs to learn in their first few days at 18F if they aren't already familiar with this.

**Comment by monfresh** [comment]
The script is configured to respond directly to a key press, so the user does not have to press enter 😄

**Comment by monfresh** [comment]
Thanks for the feedback, @stvnrlly. I will submit a follow-up PR that add instructions for switching back to bash to the README, and add a note about the password not having input feedback (although this password prompt is not new, it has always been there, as have other prompts throughout the script, and no one has mentioned this as an issue afaik). The video Wiki already includes those instructions: https://github.com/18F/laptop/wiki/Detailed-installation-instructions-with-video

**Comment by monfresh** [comment]
@brittag Thanks for the updated text. It looks great. I updated this PR with the next text, and also added a note about password input feedback and how to cancel in case you change your mind after pressing `y`.

**Comment by mogul** [comment]
Sorry I'm late to the party... I think it's important to put `Note that you can always switch back to bash if you change your mind` _before_ the prompt; otherwise it will appear to be a much bigger commitment at that point than you're trying to make it.

**Comment by monfresh** [comment]
Good point. Will update.

**Pull request merged**
