### PR TITLE
Added spectacle to the install script

### PR DESCRIPTION
**Pull request by EricSchles**
I added spectacle to the install script - it needs to be verified on someone else's laptop before being merged.  But I think spectacle would be a great tool for everyone:

https://www.spectacleapp.com/

### CODE REVIEW

**Comment by monfresh** [comment]
Thanks for the suggestion! Could you please make the following changes?

- Make Spectacle optional by putting it in [.laptop.local](https://github.com/18F/laptop/blob/master/.laptop.local)
- Use [Homebrew Cask](https://caskroom.github.io/) to install Spectacle. Take a look at [.laptop.local](https://github.com/18F/laptop/blob/master/.laptop.local#L6-L8) for examples.
- In the README, move Spectacle to the `.laptop.local` section
- Update your commit message from `updating` to a more descriptive summary and body, following this format:
    ```
    Summary under 50 characters in the imperative mood

    More information about commit (under 72 characters).
    More information about commit (under 72 characters).
    ```
   For example:
   ```
   Add Spectacle as an optional tool

   **Why**: It makes it really easy to move and resize windows.
    More info here: https://www.spectacleapp.com/
    ```

**Comment by EricSchles** [comment]
Will do!

**Comment by EricSchles** [comment]
updated pull request! @monfresh and passes on travis ci!  If you need anything else before merging please let me know!

**Comment by monfresh** [comment]
Thanks, and sorry for the late response. It looks good. Could you please remove the `.DS_Store` and `.laptop.local.swp` files? I'll follow up with a `.gitignore`.

**Comment by monfresh** [comment]
Hi @EricSchles. I'm not sure if you saw my last comment. Could you please remove the `.DS_Store` and `.laptop.local.swp` files? Thanks!

**Comment by EricSchles** [comment]
Sorry, missed this last comment - doing this now :) @monfresh

**Comment by EricSchles** [comment]
removed files and added a .gitignore so files like this aren't pushed up accidently in the future @monfresh

**Comment by monfresh** [comment]
Thanks!

**Pull request merged**
